# Generated by Django 4.2 on 2023-06-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_subscribed",
            field=models.IntegerField(default=0),
        ),
    ]
