# Generated by Django 4.2 on 2023-05-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_latitude_alter_place_longitude'),
        ('places', '0002_alter_place_latitude_alter_place_longitude_and_more'),
    ]

    operations = [
    ]
