# Generated by Django 4.2 on 2023-05-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khaltivalidation',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=100),
        ),
    ]
