# Generated by Django 4.2 on 2023-06-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
