# Generated by Django 4.2 on 2023-05-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimage',
            old_name='place',
            new_name='hotel',
        ),
    ]
