# Generated by Django 4.2 on 2023-05-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khaltivalidation',
            name='user',
        ),
    ]
