# Generated by Django 4.2 on 2023-05-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='h_name',
            field=models.CharField(default='Hotel Pokhara', max_length=255),
        ),
    ]
