# Generated by Django 4.2 on 2023-06-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_booking_h_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
